### ISSUE TITLE
Getting 403 forbidden when try to connect with dex oidc

### ISSUE THREAD

**Issue by Keerthana2496** [jaredhanson/passport-oauth2#125]
var createError = require('http-errors');
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');

var session = require('express-session');
var passport = require('passport');
var OAuth2Strategy = require('passport-oauth2').Strategy;
const HttpsProxyAgent = require('https-proxy-agent');

var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');

var app = express();
// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use(session({
  secret: 'ZXhhbXBsZS1hcHAtc2VjcmV0',
  resave: true,
  saveUninitialized: true
}));

app.use(express.static(path.join(__dirname, 'public')));

app.use(passport.initialize());
app.use(passport.session());

const oAuthStrategy = new OAuth2Strategy({
  issuer: 'http://localhost:5556/dex',
  authorizationURL: 'http://localhost:5556/dex/auth',
  tokenURL: 'http://localhost:5556/token',
  token_endpoint: 'http://localhost:5556/token',
  clientID: 'example-app',
  clientSecret: 'ZXhhbXBsZS1hcHAtc2VjcmV0',
  callbackURL : 'http://localhost:3000/callback',
  scope: 'openid',
  state: 'I wish to wash my irish wristwatch',
  passReqToCallback: true

}, function(accessToken, refreshToken, profile, cb){
      return done(null, profile);
})

// const agent = new HttpsProxyAgent(process.env.HTTP_PROXY || "http://localhost:3000");
// oAuthStrategy._oauth2.setAgent(agent);

passport.use(oAuthStrategy)

passport.serializeUser((user, next) => {
  next(null, user);
});

passport.deserializeUser((obj, next) => {
  next(null, obj);
});

app.use('/login', passport.authenticate('oauth2'))

app.use('/callback',
  passport.authenticate('oauth2',{
    failureRedirect: '/error'
  }),
  (req, res) => {  
    res.redirect('/profile');
  }
);

app.use('/profile', (req, res) => {
  console.log("user:", req);
  res.render('profile', {
    title: 'User Info'
  });
});

app.use('/', indexRouter);
app.use('/users', usersRouter);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;

For this I am getting the below error in the callback url after successful ldap authentication:

Failed to obtain access token
InternalOAuthError: Failed to obtain access token
    at OAuth2Strategy._createOAuthError (D:\reactjs\loginOAuth\sample-app\node_modules\passport-oauth2\lib\strategy.js:412:17)
    at D:\reactjs\loginOAuth\sample-app\node_modules\passport-oauth2\lib\strategy.js:178:36
    at D:\reactjs\loginOAuth\sample-app\node_modules\oauth\lib\oauth2.js:192:18
    at passBackControl (D:\reactjs\loginOAuth\sample-app\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (D:\reactjs\loginOAuth\sample-app\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

And then I added the following lines for the above error:

const agent = new HttpsProxyAgent(process.env.HTTP_PROXY || "http://localhost:3000");
oAuthStrategy._oauth2.setAgent(agent);
passport.use(oAuthStrategy)

Now I am getting 403 Forbidden error message in the callback url.
I am stuck in this. Pls guide me through right direction. Thanks in advance!

**Comment by david114** [comment]
Have you found a solution to this problem?
I'm exactly stuck at the same problem right now.

**Comment by cab404** [comment]
Wow, 6 hours apart.
I too am having a similar problem with dex.

```
TokenError: Invalid client credentials.
    at OAuth2Strategy.parseErrorResponse (/nix/store/ad6m7b07hbbk7hrbv60r0n7rzyb0hfjd-outline-0.66.1/share/outline/node_modules/passport-oauth2/lib/strategy.js:373:12)
    at OAuth2Strategy._createOAuthError (/nix/store/ad6m7b07hbbk7hrbv60r0n7rzyb0hfjd-outline-0.66.1/share/outline/node_modules/passport-oauth2/lib/strategy.js:420:16)
    at /nix/store/ad6m7b07hbbk7hrbv60r0n7rzyb0hfjd-outline-0.66.1/share/outline/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /nix/store/ad6m7b07hbbk7hrbv60r0n7rzyb0hfjd-outline-0.66.1/share/outline/node_modules/oauth/lib/oauth2.js:191:18\n    at passBackControl (/nix/store/ad6m7b07hbbk7hrbv60r0n7rzyb0hfjd-outline-0.66.1/share/outline/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/nix/store/ad6m7b07hbbk7hrbv60r0n7rzyb0hfjd-outline-0.66.1/share/outline/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by cab404** [comment]
> @cab404 Are you using this inside a docker container? Inside a docker container I always get `Failed to obtain access token `error. Without docker it works perfectly fine. Using dex too btw.

Actually, I solved it for my case recently. It was quite an interesting Dex oversight – Dex doesn't use environment variable expansion in the list of client configs – so you would literally get $ENV_VAR as a value.
