### ISSUE TITLE
crash since the last version when authenticating

### ISSUE THREAD

**Issue by rafipiccolo** [jaredhanson/passport-oauth2#146]
it used to work well, and the new version broke the website.
authentication now crashes server

passport-facebook 3.0.0
which uses passport-oauth2 1.5.0
passport 0.5.0
node v16.10.0

here is the stack trace :
```
uncaughtException req.logIn is not a function {
     "err": {
         "code": null,
         "name": "TypeError",
         "message": "req.logIn is not a function",
         "detail": null,
         "stack": [
             "TypeError: req.logIn is not a function",
             "    at Strategy.strategy.success (/usr/app/node_modules/passport/lib/middleware/authenticate.js:247:13)",
             "    at verified (/usr/app/node_modules/passport-oauth2/lib/strategy.js:186:20)",
             "    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
         ],
         "err": null
     }
```

it may only be a typo in the lib in the new version ?

this is my implementation :

```
let FacebookStrategy = require('passport-facebook').Strategy;

        async function facebookConnect(req, accessToken, refreshToken, profile) {
            let user = ...;
            
            return user;
        }

        passport.use(
            new FacebookStrategy(config.facebook, (req, accessToken, refreshToken, profile, callback) => {
                profile = profile._json;

                require('util').callbackify(facebookConnect)(req, accessToken, refreshToken, profile, callback);
            })
        );

        app.get(
            '/auth/facebook',
            passport.authenticate('facebook', {
                authType: 'rerequest',
                scope: ['email', 'public_profile'],
            })
        );

        app.get(
            '/auth/facebook/callback',
            passport.authenticate('facebook', {
                session: false,
                failureRedirect: '/login',
            }),
            (req, res, next) => {
                res.redirect('/');
            }
        );
```

**Comment by rafipiccolo** [comment]
solved by calling app.use(passport.initialize()) before app.get('...', passport.auhenticate(...)) calls

https://github.com/jaredhanson/passport/issues/854
