### ISSUE TITLE
--pending-deprecation DeprecationWarning: `url.parse()`

### ISSUE THREAD

**Issue by CodeIter** [jaredhanson/passport-oauth2#181]
Hi, I found a pending deprecation hier:

https://github.com/jaredhanson/passport-oauth2/blob/ea9e99adda82dff67502654347589866fea80eb2/lib/strategy.js#L103

I used This  NODE_OPTIONS:
```bash
NODE_OPTIONS="--pending-deprecation --throw-deprecation --trace-deprecation"
```

Output:
```
+ node server.mjs
node:internal/process/warning:162
        throw warning;
        ^

DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
    at Object.urlParse [as parse] (node:url:154:13)
    at Strategy.OAuth2Strategy (.../myproject/node_modules/.pnpm/passport-oauth2@1.7.0/node_modules/passport-oauth2/lib/strategy.js:103:54)
    at new Strategy (.../myproject/node_modules/.pnpm/passport-facebook@3.0.0/node_modules/passport-facebook/lib/strategy.js:56:18)
    at file://.../myproject/src/auth/strategy/facebook.mjs:7:33
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25) {
  code: 'DEP0169'
}

Node.js v20.2.0

Fail : Code status 1

```

**Comment by svenbledt** [comment]
[passport-oauth2+1.8.0.patch](https://github.com/user-attachments/files/25260790/passport-oauth2%2B1.8.0.patch)

I know i could've done a pull request for this fix but the short solution i used was to patch it. Here i share the patch for you guys so you can easy implement my changes and the deprecation uses the new WHATWG URL API 

i hope it helps
