### ISSUE TITLE
TokenError 

### ISSUE THREAD

**Issue by joh-klein** [jaredhanson/passport-oauth2#66]
My OAuth2-Server emits this error Message:

> { statusCode: 400, data: '{"error":"invalid_client"}' }

whenever there is something wrong with app id or app secret. This leads to a very prominent and ugly error message for the user(s) (right in the browser):

> TokenError
   at OAuth2Strategy.parseErrorResponse (/app/node_modules/passport-oauth2/lib/strategy.js:320:12)
   at OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:367:16)
   at /app/node_modules/passport-oauth2/lib/strategy.js:166:46
   at /app/node_modules/oauth/lib/oauth2.js:195:7
   at passBackControl (/app/node_modules/oauth/lib/oauth2.js:125:9)
   at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:143:7)
   at emitNone (events.js:91:20)
   at IncomingMessage.emit (events.js:185:7)
   at endReadableNT (_stream_readable.js:974:12)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)

What can be done, that I can either catch this error or at least have it be less end-of-the-worldy for the app users?

**Comment by joh-klein** [comment]
That was premature. I ended up doing some proper error handling in ExpressJS.
