### ISSUE TITLE
Consider adding debug options

### ISSUE THREAD

**Issue by jonathansamines** [jaredhanson/passport-oauth2#90]
Sometimes when something is not setup properly (not the module fault, but mainly because weird server configurations), it becomes hard to debug and determine what the underlying error is. Would you consider adding the "debug" module to help with that matter?

Thanks!

**Comment by blaskovicz** [comment]
Even just changing the following line helped me immensely to see the real issue:

## code
```
--- a/lib/strategy.js
+++ b/lib/strategy.js
@@ -163,7 +163,10 @@ OAuth2Strategy.prototype.authenticate = function(req, options) {

       self._oauth2.getOAuthAccessToken(code, params,
         function(err, accessToken, refreshToken, params) {
-          if (err) { return self.error(self._createOAuthError('Failed to obtain access token', err)); }
+          if (err) {
+            console.warn("Failed to obtain access token: ", err);
+            return self.error(self._createOAuthError('Failed to obtain access token', err));
+          }
```
## issue
```
2017-09-28T18:22:47.249104Z app[web.1]: Failed to obtain access token:  { Error: self signed certificate in certificate chain
2017-09-28T18:22:47.249143Z app[web.1]:     at Error (native)
2017-09-28T18:22:47.249171Z app[web.1]:     at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
2017-09-28T18:22:47.249184Z app[web.1]:     at emitNone (events.js:86:13)
2017-09-28T18:22:47.2492Z app[web.1]:     at TLSSocket.emit (events.js:185:7)
2017-09-28T18:22:47.249211Z app[web.1]:     at TLSSocket._finishInit (_tls_wrap.js:586:8)
2017-09-28T18:22:47.249255Z app[web.1]:     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
```
vs.

```
2017-09-28T18:22:47.253492Z app[web.1]: InternalOAuthError: Failed to obtain access token
2017-09-28T18:22:47.253533Z app[web.1]:     at OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:382:17)
2017-09-28T18:22:47.253555Z app[web.1]:     at /app/node_modules/passport-oauth2/lib/strategy.js:168:36
2017-09-28T18:22:47.253566Z app[web.1]:     at /app/node_modules/oauth/lib/oauth2.js:191:18
2017-09-28T18:22:47.253577Z app[web.1]:     at ClientRequest.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:162:5)
2017-09-28T18:22:47.253588Z app[web.1]:     at emitOne (events.js:96:13)
2017-09-28T18:22:47.253599Z app[web.1]:     at ClientRequest.emit (events.js:188:7)
2017-09-28T18:22:47.253609Z app[web.1]:     at TLSSocket.socketErrorListener (_http_client.js:310:9)
2017-09-28T18:22:47.253625Z app[web.1]:     at emitOne (events.js:96:13)
```
## notes

It seems like the second argument to `self._createOAuthError` doesn't actually get used in this case:

```
OAuth2Strategy.prototype._createOAuthError = function(message, err) {
  var e;
  if (err.statusCode && err.data) {
    try {
      e = this.parseErrorResponse(err.data, err.statusCode);
    } catch (_) {}
  }
  if (!e) { e = new InternalOAuthError(message, err); }
  return e;
};
```

**Comment by ChrisSamo632** [comment]
This change appears to have been reverted, there are no useful logs output when the `_createOAuthError` function is triggered 🙁

**Comment by ChrisSamo632** [comment]
It's possible to extend the OAuth2Strategy and replace the `_createOAuthError` function to add more useful logging, e.g.

```typescript
import { Agent } from 'https';
import OAuth2Strategy, { InternalOAuthError, TokenError } from 'passport-oauth2';
import util from 'util';

declare class OAuth2LoggingStrategy extends OAuth2Strategy {
  constructor(options: OAuth2Strategy.StrategyOptions, verify: OAuth2Strategy.VerifyFunction);
  constructor(
    options: OAuth2Strategy.StrategyOptionsWithRequest,
    verify: OAuth2Strategy.VerifyFunctionWithRequest
  );

  // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/explicit-module-boundary-types
  _createOAuthError(message: string, err: any): any;
}

function OAuth2LoggingStrategy(
  this: OAuth2Strategy,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/explicit-module-boundary-types
  options: any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/explicit-module-boundary-types
  verify: any
): void {
  OAuth2Strategy.call(this, options, verify);
}

util.inherits(OAuth2LoggingStrategy, OAuth2Strategy);

// eslint-disable-next-line @typescript-eslint/no-explicit-any
OAuth2LoggingStrategy.prototype._createOAuthError = function (message: string, err: any) {
  let e = null;
  if (err) {
    console.warn(`Create OAuthError [${message}] for err: ${JSON.stringify(err)}`);

    if (err.statusCode && err.data) {
      try {
        const json = JSON.parse(err.data);
        if (json.error) {
          e = new TokenError(json.error_description, json.error, json.error_uri);
        }
      } catch (e2) {
        console.error(`Unable to parse Error response: ${JSON.stringify(e2)}`);
      }
    }
  } else {
    console.warn(`Create OAuthError [${message}] for err: undefined`);
  }

  if (!e) {
    e = new InternalOAuthError(message, err);
  }

  return e;
};

export default OAuth2LoggingStrategy;
```
